// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmc1ja-1CfKXjueG9elWI1ybDIyhvOwwQ',
    appId: '1:934180597657:web:a3a63de3dac2ae633ead08',
    messagingSenderId: '934180597657',
    projectId: 'majorproject-84801',
    authDomain: 'majorproject-84801.firebaseapp.com',
    storageBucket: 'majorproject-84801.firebasestorage.app',
    measurementId: 'G-R0WCT1VF8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxoEA4fjupEvpgUYChFp45zdN52sHXVo',
    appId: '1:934180597657:android:34797a2cb1b707993ead08',
    messagingSenderId: '934180597657',
    projectId: 'majorproject-84801',
    storageBucket: 'majorproject-84801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjf0lUEP5vq28gLhetmidnQxSaBNfZu9I',
    appId: '1:934180597657:ios:1dbdb0f9adf321e13ead08',
    messagingSenderId: '934180597657',
    projectId: 'majorproject-84801',
    storageBucket: 'majorproject-84801.firebasestorage.app',
    iosBundleId: 'com.example.crowdAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjf0lUEP5vq28gLhetmidnQxSaBNfZu9I',
    appId: '1:934180597657:ios:1dbdb0f9adf321e13ead08',
    messagingSenderId: '934180597657',
    projectId: 'majorproject-84801',
    storageBucket: 'majorproject-84801.firebasestorage.app',
    iosBundleId: 'com.example.crowdAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmc1ja-1CfKXjueG9elWI1ybDIyhvOwwQ',
    appId: '1:934180597657:web:08fbd43b8e38edef3ead08',
    messagingSenderId: '934180597657',
    projectId: 'majorproject-84801',
    authDomain: 'majorproject-84801.firebaseapp.com',
    storageBucket: 'majorproject-84801.firebasestorage.app',
    measurementId: 'G-F1Q3PJ7PT8',
  );
}
